name: Deploy API (NestJS) 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy API to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/zenn/zenn_api
            git pull origin main
            npm install
            npm run build
            pm2 describe zenn-api > /dev/null \
              && pm2 restart zenn-api \
              || pm2 start dist/main.js --name zenn-api
            pm2 save
